#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("L07.Resource", IsApplication=true)]

namespace L07
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int i01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int i02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int i03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int i04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int i05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int i06 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int i07 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int i08 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int i09 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int i10 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int i11 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int i12 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int button1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int chk = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int image = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int listView = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RowItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
